spring.application.name=Api-rojas-remodeling
server.port=${PORT:8081}


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=${SHOW_SQL:true}


jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}


supabase.url=${SUPABASE_URL}
supabase.key=${SUPABASE_KEY}
supabase.bucket=${SUPABASE_BUCKET}


brevo.api.key=${BREVO_API_KEY}

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB