spring.application.name=Api-rojas-remodeling
server.port=${PORT:8081}


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=${SHOW_SQL:true}


jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}


supabase.url=${SUPABASE_URL}
supabase.key=${SUPABASE_KEY}
supabase.bucket=${SUPABASE_BUCKET}


brevo.api.key=${BREVO_API_KEY}

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=2525
spring.mail.username=9ea38d001@smtp-brevo.com  
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.protocol=smtp

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable=false


spring.mail.properties.mail.smtp.ssl.trust=*


spring.mail.properties.mail.smtp.connectiontimeout=15000
spring.mail.properties.mail.smtp.timeout=15000
spring.mail.properties.mail.smtp.writetimeout=15000

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB