spring.application.name=Api-rojas-remodeling

spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.ygnwmndhloxlpfmlmptu
spring.datasource.password=5hHhKkF10daFJN93
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8081

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
jwt.secret=mi_clave_ultra_segura_12345678901234567890123456789012345678901234567890
jwt.expiration=86400000


supabase.url=https://ygnwmndhloxlpfmlmptu.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlnbndtbmRobG94bHBmbWxtcHR1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3ODE1NzU5NSwiZXhwIjoyMDkzNzMzNTk1fQ.a2faWIttfHtSiiK61ml5qvoQf0_LWmHF7uTRCAXFrXQ
supabase.bucket=evidences
